debug_mode: False

role_info:
    is_client: False
    id: 'edge-01'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '127.0.0.1'

message_info:
    msg:
        is_tcp: True
        port: 20001
    odm:
        is_tcp: True
        port: 20002
    path:
        is_tcp: True
        port: 20003
    cmd:
        is_tcp: True
        port: 20004
    img:
        is_tcp: True
        port: 20005
        width: 640
        height: 480
    ctrl:
        is_tcp: True
        port: 20006
