debug_mode: False
use_log: True
robot_id: 0

role_info:
    is_client: False
    id: 'edge-01'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '127.0.0.1'

message_info:
    state:
        is_tcp: True
        port: 31000
    img:
        is_tcp: True
        port: 32000
        width: 640
        height: 480
    cmd:
        is_tcp: True
        port: 33000
